/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
  /**
   * 要查找的工作目录路径
   * @type {string}
   * @memberof InlineObject2
   */
  cwd: string;
}

export function InlineObject2FromJSON(json: any): InlineObject2 {
  return InlineObject2FromJSONTyped(json, false);
}

export function InlineObject2FromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineObject2 {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    cwd: json["cwd"],
  };
}

export function InlineObject2ToJSON(value?: InlineObject2 | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    cwd: value.cwd,
  };
}
