/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
  type InlineResponse2001SessionMetrics,
  InlineResponse2001SessionMetricsFromJSON,
  InlineResponse2001SessionMetricsToJSON,
} from "./index.ts";

/**
 * 会话信息
 * @export
 * @interface InlineResponse2001Session
 */
export interface InlineResponse2001Session {
  /**
   * 会话开始时间
   * @type {Date}
   * @memberof InlineResponse2001Session
   */
  sessionStartTime?: Date;
  /**
   * 提示词计数
   * @type {number}
   * @memberof InlineResponse2001Session
   */
  promptCount?: number;
  /**
   * 最后提示词token计数
   * @type {number}
   * @memberof InlineResponse2001Session
   */
  lastPromptTokenCount?: number;
  /**
   *
   * @type {InlineResponse2001SessionMetrics}
   * @memberof InlineResponse2001Session
   */
  metrics?: InlineResponse2001SessionMetrics;
}

export function InlineResponse2001SessionFromJSON(
  json: any
): InlineResponse2001Session {
  return InlineResponse2001SessionFromJSONTyped(json, false);
}

export function InlineResponse2001SessionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001Session {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sessionStartTime: !exists(json, "sessionStartTime")
      ? undefined
      : new Date(json["sessionStartTime"]),
    promptCount: !exists(json, "promptCount") ? undefined : json["promptCount"],
    lastPromptTokenCount: !exists(json, "lastPromptTokenCount")
      ? undefined
      : json["lastPromptTokenCount"],
    metrics: !exists(json, "metrics")
      ? undefined
      : InlineResponse2001SessionMetricsFromJSON(json["metrics"]),
  };
}

export function InlineResponse2001SessionToJSON(
  value?: InlineResponse2001Session | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sessionStartTime:
      value.sessionStartTime === undefined
        ? undefined
        : value.sessionStartTime.toISOString(),
    promptCount: value.promptCount,
    lastPromptTokenCount: value.lastPromptTokenCount,
    metrics: InlineResponse2001SessionMetricsToJSON(value.metrics),
  };
}
