/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime.ts";
import {
  type InlineResponse2001SessionMetricsTools,
  InlineResponse2001SessionMetricsToolsFromJSON,
  InlineResponse2001SessionMetricsToolsToJSON,
  type ModelMetrics,
  ModelMetricsFromJSON,
  ModelMetricsToJSON,
} from "./index.ts";

/**
 * 指标数据
 * @export
 * @interface InlineResponse2001SessionMetrics
 */
export interface InlineResponse2001SessionMetrics {
  /**
   *
   * @type {{ [key: string]: ModelMetrics; }}
   * @memberof InlineResponse2001SessionMetrics
   */
  models?: { [key: string]: ModelMetrics };
  /**
   *
   * @type {InlineResponse2001SessionMetricsTools}
   * @memberof InlineResponse2001SessionMetrics
   */
  tools?: InlineResponse2001SessionMetricsTools;
}

export function InlineResponse2001SessionMetricsFromJSON(
  json: any
): InlineResponse2001SessionMetrics {
  return InlineResponse2001SessionMetricsFromJSONTyped(json, false);
}

export function InlineResponse2001SessionMetricsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001SessionMetrics {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    models: !exists(json, "models")
      ? undefined
      : mapValues(json["models"], ModelMetricsFromJSON),
    tools: !exists(json, "tools")
      ? undefined
      : InlineResponse2001SessionMetricsToolsFromJSON(json["tools"]),
  };
}

export function InlineResponse2001SessionMetricsToJSON(
  value?: InlineResponse2001SessionMetrics | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    models:
      value.models === undefined
        ? undefined
        : mapValues(value.models, ModelMetricsToJSON),
    tools: InlineResponse2001SessionMetricsToolsToJSON(value.tools),
  };
}
