/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
import {
  type InlineResponse2001SessionMetricsToolsTotalDecisions,
  InlineResponse2001SessionMetricsToolsTotalDecisionsFromJSON,
  InlineResponse2001SessionMetricsToolsTotalDecisionsToJSON,
} from "./index.ts";

/**
 * 工具调用统计
 * @export
 * @interface InlineResponse2001SessionMetricsTools
 */
export interface InlineResponse2001SessionMetricsTools {
  /**
   * 总调用次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  totalCalls?: number;
  /**
   * 成功调用次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  totalSuccess?: number;
  /**
   * 失败调用次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  totalFail?: number;
  /**
   * 总耗时(毫秒)
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  totalDurationMs?: number;
  /**
   *
   * @type {InlineResponse2001SessionMetricsToolsTotalDecisions}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  totalDecisions?: InlineResponse2001SessionMetricsToolsTotalDecisions;
  /**
   * 按工具名称统计
   * @type {object}
   * @memberof InlineResponse2001SessionMetricsTools
   */
  byName?: object;
}

export function InlineResponse2001SessionMetricsToolsFromJSON(
  json: any
): InlineResponse2001SessionMetricsTools {
  return InlineResponse2001SessionMetricsToolsFromJSONTyped(json, false);
}

export function InlineResponse2001SessionMetricsToolsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001SessionMetricsTools {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    totalCalls: !exists(json, "totalCalls") ? undefined : json["totalCalls"],
    totalSuccess: !exists(json, "totalSuccess")
      ? undefined
      : json["totalSuccess"],
    totalFail: !exists(json, "totalFail") ? undefined : json["totalFail"],
    totalDurationMs: !exists(json, "totalDurationMs")
      ? undefined
      : json["totalDurationMs"],
    totalDecisions: !exists(json, "totalDecisions")
      ? undefined
      : InlineResponse2001SessionMetricsToolsTotalDecisionsFromJSON(
          json["totalDecisions"]
        ),
    byName: !exists(json, "byName") ? undefined : json["byName"],
  };
}

export function InlineResponse2001SessionMetricsToolsToJSON(
  value?: InlineResponse2001SessionMetricsTools | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    totalCalls: value.totalCalls,
    totalSuccess: value.totalSuccess,
    totalFail: value.totalFail,
    totalDurationMs: value.totalDurationMs,
    totalDecisions: InlineResponse2001SessionMetricsToolsTotalDecisionsToJSON(
      value.totalDecisions
    ),
    byName: value.byName,
  };
}
