/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists } from "../runtime.ts";
/**
 * 决策统计
 * @export
 * @interface InlineResponse2001SessionMetricsToolsTotalDecisions
 */
export interface InlineResponse2001SessionMetricsToolsTotalDecisions {
  /**
   * 接受次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsToolsTotalDecisions
   */
  accept?: number;
  /**
   * 拒绝次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsToolsTotalDecisions
   */
  reject?: number;
  /**
   * 修改次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsToolsTotalDecisions
   */
  modify?: number;
}

export function InlineResponse2001SessionMetricsToolsTotalDecisionsFromJSON(
  json: any
): InlineResponse2001SessionMetricsToolsTotalDecisions {
  return InlineResponse2001SessionMetricsToolsTotalDecisionsFromJSONTyped(
    json,
    false
  );
}

export function InlineResponse2001SessionMetricsToolsTotalDecisionsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001SessionMetricsToolsTotalDecisions {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    accept: !exists(json, "accept") ? undefined : json["accept"],
    reject: !exists(json, "reject") ? undefined : json["reject"],
    modify: !exists(json, "modify") ? undefined : json["modify"],
  };
}

export function InlineResponse2001SessionMetricsToolsTotalDecisionsToJSON(
  value?: InlineResponse2001SessionMetricsToolsTotalDecisions | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    accept: value.accept,
    reject: value.reject,
    modify: value.modify,
  };
}
