/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2001SessionMetricsApi
 */
export interface InlineResponse2001SessionMetricsApi {
  /**
   * 总API请求次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsApi
   */
  totalRequests: number;
  /**
   * 总API错误次数
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsApi
   */
  totalErrors: number;
  /**
   * 总延迟时间（毫秒）
   * @type {number}
   * @memberof InlineResponse2001SessionMetricsApi
   */
  totalLatencyMs: number;
}

export function InlineResponse2001SessionMetricsApiFromJSON(
  json: any
): InlineResponse2001SessionMetricsApi {
  return InlineResponse2001SessionMetricsApiFromJSONTyped(json, false);
}

export function InlineResponse2001SessionMetricsApiFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InlineResponse2001SessionMetricsApi {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    totalRequests: json["totalRequests"],
    totalErrors: json["totalErrors"],
    totalLatencyMs: json["totalLatencyMs"],
  };
}

export function InlineResponse2001SessionMetricsApiToJSON(
  value?: InlineResponse2001SessionMetricsApi | null
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    totalRequests: value.totalRequests,
    totalErrors: value.totalErrors,
    totalLatencyMs: value.totalLatencyMs,
  };
}
