/* tslint:disable */
/* eslint-disable */
/**
 * qwen-code-api-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    type InlineResponse2001SessionMetricsApi,
    InlineResponse2001SessionMetricsApiFromJSON, InlineResponse2001SessionMetricsApiToJSON,
    type InlineResponse2001SessionMetricsTokens,
    InlineResponse2001SessionMetricsTokensFromJSON, InlineResponse2001SessionMetricsTokensToJSON
} from './index.ts';

/**
 * ModelMetrics
 * @export
 * @interface ModelMetrics
 */
export interface ModelMetrics {
    /**
     * 
     * @type {InlineResponse2001SessionMetricsApi}
     * @memberof ModelMetrics
     */
    api: InlineResponse2001SessionMetricsApi;
    /**
     * 
     * @type {InlineResponse2001SessionMetricsTokens}
     * @memberof ModelMetrics
     */
    tokens: InlineResponse2001SessionMetricsTokens;
}

export function ModelMetricsFromJSON(json: any): ModelMetrics {
    return ModelMetricsFromJSONTyped(json, false);
}

export function ModelMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelMetrics {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'api': InlineResponse2001SessionMetricsApiFromJSON(json['api']),
        'tokens': InlineResponse2001SessionMetricsTokensFromJSON(json['tokens']),
    };
}

export function ModelMetricsToJSON(value?: ModelMetrics | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'api': InlineResponse2001SessionMetricsApiToJSON(value.api),
        'tokens': InlineResponse2001SessionMetricsTokensToJSON(value.tokens),
    };
}


